### PR TITLE
Fix the invalid topic basename errors for certain vehicle classes

### LINKED ISSUE #46: invalid topic / invalid basename errors for certain vehicle classes
While testing #45, I bought some vehicles from the store which apparently have type names which contained some characters "illegal" in a ROS resource name. This resulted in the following warnings:

```
[ERROR] [1631884756.569664824]: isSubtopic() Invalid topic: Character [-] at element [12] is not valid in Graph Resource Name [/ropa_nawaro-maus_111/imu].  Valid characters are a-z, A-Z, 0-9, / and _.
[ERROR] [1631884756.569725723]: isSubtopic() Invalid basename: Character [-] at element [12] is not valid in Graph Resource Name [/ropa_nawaro-maus_111/imu].  Valid characters are a-z, A-Z, 0-9, / and _.
[ERROR] [1631884756.569755232]: isSubtopic() Invalid basename: Character [-] at element [12] is not valid in Graph Resource Name [/ropa_nawaro-maus_111/odom].  Valid characters are a-z, A-Z, 0-9, / and _.
```

seems we need to fix [ros.names.Sanatize(..)](https://github.com/tud-cor/FS19_modROS/blob/c94ccecac93595599943d8faeab74e246933ce04/src/utils/ros.lua#L27-L31).

### PR DESCRIPTION
**Pull request by tckarenchiang**
This PR is to fix #46.

Now every illegal character, namely non-alphanumeric character is replaced with an underscore (`_`).

### CODE REVIEW

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
This is much better, but there are two corner cases I believe we need to address as well:

 - names starting with an illegal char
 - names ending in an illegal char

Example: `manitou_mla-t_533-145_v+`, which becomes: `manitou_mla_t_533_145_v_`. Note the `_` at the end.

That's not really nice as a ROS resource name. Perhaps add a check to make sure names do not start or end with underscores?

**Comment by tckarenchiang** [comment]
> make sure names do not start or end with underscores?

I've added a check for both cases. Thanks for the suggestion.

File: src/utils/ros.lua [hunk 1]
```diff
@@ -26,8 +26,23 @@ ros.Time = {}
 
 -- function for legalizing a name for ROS resources
 function ros.Names.sanatize(veh_name)
-    -- replace whitespace with underscores and uppercase with lowercase to meet the ROS naming conventions for TF
-    return veh_name:gsub(" ", "_"):lower()
+    -- in order to meet the ROS naming conventions, we need to sanitize illegal names from FS by using
+    -- 1. "%W" to replace every non-alphanumeric character with an underscore "_"
+    -- 2. "+" modifier to get the longest sequence of non-alphanumeric character, i.e. "___" -> "_" (replace consecutive _ with single _)
+    -- 3. :lower() to replace every uppercase letter with lowercase one
+    veh_name = veh_name:gsub("%W+", "_"):lower()
```
Comment (gavanderhoorn) [inline src/utils/ros.lua:33]: I only noticed this now: we should not be changing `veh_name` "in place".

We should create a new `local` var and return that.

File: src/utils/ros.lua [hunk 2]
```diff
@@ -26,8 +26,23 @@ ros.Time = {}
...
+
+    -- make sure names do not start or end with underscores
+    -- if it starts with an underscore, remove the first character
+    if veh_name:sub(1,1) == "_" then
+        veh_name = veh_name:sub(2,-1)
+    end
```
Comment (gavanderhoorn) [inline src/utils/ros.lua:39]: If I understand [Lua for Python Programmers: strings](http://the4thwiki.com/lua/strings.html) correctly, the `-1` should be unnecessary, right? We just want the string, skipping the first character.

What about using `gsub(..)` here again as an alternative? Something like:


```suggestion
veh_name = veh_name:gsub("^_+", "")
```

File: src/utils/ros.lua [hunk 3]
```diff
@@ -26,8 +26,23 @@ ros.Time = {}
...
+
+    -- if it ends with an underscore, remove the last character
+    if veh_name:sub(-1,-1) == "_" then
+        veh_name = veh_name:sub(1,-2)
+    end
```
Comment (gavanderhoorn) [inline src/utils/ros.lua:44]: same here, `gsub(..)` could be used.

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]

File: src/utils/ros.lua (hunk 1 above)
Comment (tckarenchiang) [reply src/utils/ros.lua]: Thanks! I've created a local variable.

File: src/utils/ros.lua (hunk 2 above)
Comment (tckarenchiang) [reply src/utils/ros.lua]: you are right. it's not necessary.

Is `+` necessary here? Since we've already [replaced all the consecutive `_` with single `_` ](https://github.com/tckarenchiang/FS19_modROS/blob/fix_invalid_topic/src/utils/ros.lua#L33).

File: src/utils/ros.lua (hunk 3 above)
Comment (tckarenchiang) [reply src/utils/ros.lua]: same here. Is `+` necessary?

File: src/utils/ros.lua (hunk 2 above)
Comment (tckarenchiang) [reply src/utils/ros.lua]: ok, I removed it.

**Review by gavanderhoorn — APPROVED** [review]
Haven't tested it with FS, but this seems like it should be ok.

Thanks for iterating @tckarenchiang :+1:

**Comment by tckarenchiang** [comment]
> Haven't tested it with FS, but this seems like it should be ok.
> 
> Thanks for iterating @tckarenchiang 👍

I did test it with `manitou_mla-t_533-145_v+`. It seems ok!
