### PR TITLE
Make sure the player is in the vehicle before running rosPubMsg

### LINKED ISSUE #25: rosPubMsg: attempt to index field 'vehicle' (a nil value)
After following the installation instructions, starting FS19, **not** getting in any vehicle and then immediately executing `rosPubMsg true` in the game console gets me this:

```
2021-06-03 16:47 Error: Running LUA method 'rosPubMsg'.
2021-06-03 16:47 C:/Users/user/Documents/My Games/FarmingSimulator2019/mods/modROS/modROS.lua:506: attempt to index field 'vehicle' (a nil value)
2021-06-03 16:47 Warning (script): 'localToWorld': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2021-06-03 16:47   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-06-03 16:47 LUA call stack:
2021-06-03 16:47   =C:/Users/user/Documents/My Games/FarmingSimulator2019/mods/modROS/modROS.lua (298) : localToWorld
2021-06-03 16:47   =C:/Users/user/Documents/My Games/FarmingSimulator2019/mods/modROS/modROS.lua (115) : publish_laser_scan_func
2021-06-03 16:47   dataS/scripts/BaseMission.lua (1599) : update
2021-06-03 16:47   dataS/scripts/FSBaseMission.lua (1979) : update
2021-06-03 16:47   dataS/scripts/missions/mission00.lua (469) : update
2021-06-03 16:47   dataS/scripts/main.lua (1944) : update
```

the line mentioned is here:

https://github.com/tud-cor/FS19_modROS/blob/0424021c54f95efb26e6a6cef709a7ad547cf61e/modROS.lua#L504-L506

the error makes sense: I'm not in a vehicle, so `g_currentMission.controlledVehicle` is `nil`.

### PR DESCRIPTION
**Pull request by tckarenchiang**
This is to fix #25

### CODE REVIEW

File: modROS.lua [hunk 1]
```diff
@@ -505,32 +506,38 @@ function ModROS:rosPubMsg(flag)
...
-            self.instance_veh.vehicle.components,
-            camIndexStr,
-            self.instance_veh.vehicle.i3dMappings
-        )
-        if self.instance_veh.cameraNode == nil then
-            print("nil camera")
-        -- else
-        --     print(instance_veh.cameraNode)
+        -- if the player is not in the vehicle, print error and return
+        if not vehicle then
```
Comment (gavanderhoorn) [inline modROS.lua:512]: This will avoid the `nil` related error, but should `self.rosPubMsg` also not be reset to `false` in this case?

Otherwise I believe `ModROS:update(..)` will try to still publish data, right?

Comment (gavanderhoorn) [reply modROS.lua:512]: And in that case we should probably also guard the opening of the pipe file, otherwise that will be attempted multiple times.

**Comment by gavanderhoorn** [comment]
For future development it might be best to decouple "being in a vehicle" and initialising the publishing infrastructure.

That would seem to be necessary for #3 anyway.

File: modROS.lua (hunk 1 above)
Comment (tckarenchiang) [reply modROS.lua:512]: But 1cb72b506df81b10f96cde28c193726d97722587 also avoids publishing data if the player is not in a vehicle

Comment (gavanderhoorn) [reply modROS.lua:512]: But why even continue with `rosPubMsg(..)` if it's clear the player is not in a vehicle?

By adding more conditionals everywhere it looks like we're just complicating things which could be kept simple.

Comment (tckarenchiang) [reply modROS.lua:512]: because initially I wanted to control the inactive vehicles as well.

Comment (gavanderhoorn) [reply modROS.lua:512]: So are you planning to change anything, or should we merge this version?

Comment (tckarenchiang) [reply modROS.lua:512]: yes, we should just merge this version for now. Even though it's not a proper fix, it does solve the issue I believe.

**Review by gavanderhoorn — APPROVED** [review]
Ok, let's address the immediate issue.

**Comment by gavanderhoorn** [comment]
@tckarenchiang: this will need a rebase I believe.

**Comment by tckarenchiang** [comment]
> @tckarenchiang: this will need a rebase I believe.

**Comment by tckarenchiang** [comment]
sorry I accidentally clicked `close with comment`
